"""
AI Generator — uses OpenAI to create product listings following the rules document.
Also generates product images via DALL-E.
"""

import os
import json
import base64
import requests
from openai import OpenAI
from google import genai

client = None
gemini_client = None

def init_openai():
    global client
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def init_gemini():
    global gemini_client
    gemini_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


LISTING_SYSTEM_PROMPT = """You are a Shopify product listing expert for a UK industrial store.
You create professional product listings from scraped product data.

STRICT RULES:
1. TITLE: Main Keyword – Size (if needed) – Colour – Important Detail – Use Case
   If multiple sizes/colours exist as variants, don't put them in title.

2. DESCRIPTION in this exact order:
   - Short Description (3-4 lines, NO heading above it — just the text directly, no "Short Description" heading)
   - Specifications (with heading)
   - Features (with heading)
   - Benefits (with heading)
   - Use Cases (with heading)
   - FAQ (2-3 Q&As, last section)

3. SPECIFICATIONS: Extract ALL technical data from the source. Rewrite in your own words. Include ALL measurements. Use structured format.

4. PRODUCT TYPE: Must match the collection name exactly.

5. TAGS: Include collection name, original product title, website name (without .com/.co.uk)

6. VARIANTS: Include ALL variants exactly as shown — sizes, colours, dimensions. Do NOT miss any. Do NOT guess.

7. PRICING: Selling price = reference price (inc VAT) × 2

8. INVENTORY: Always disabled.

9. DO NOT INCLUDE: Brand names, website names, emails, phones, shipping info, links, image URLs.

OUTPUT FORMAT — Return valid JSON:
{
  "title": "Product Title Following The Rule",
  "body_html": "<p>Short description text here without any heading...</p><h3>Specifications</h3><p>...</p><h3>Features</h3><ul>...</ul><h3>Benefits</h3><p>...</p><h3>Use Cases</h3><p>...</p><h3>FAQ</h3><p>...</p>",
  "product_type": "Collection Name",
  "tags": ["tag1", "tag2", "tag3"],
  "variants": [
    {
      "option1": "Size/Option Value",
      "price": "29.99",
      "sku": "",
      "inventory_management": null,
      "inventory_policy": "continue"
    }
  ],
  "options": [
    {
      "name": "Size",
      "values": ["Value1", "Value2"]
    }
  ],
  "image_prompt_1": "Detailed prompt for primary product image...",
  "image_prompt_2": "Detailed prompt for use-case image..."
}

IMPORTANT:
- All prices must be 2x the reference price (inc VAT)
- body_html must be valid HTML
- Include ALL variants found in the data
- If only one variant/size, still create one variant entry
- Generate detailed image prompts following the image rules (real-life use, 1000x1000, no text, no logos, no installation scenes)
"""


def generate_listing(product_data, collection_name, website_name):
    """Generate a Shopify product listing from scraped product data."""
    if not client:
        init_openai()

    # Build context from scraped data
    context = f"""
COLLECTION NAME: {collection_name}
WEBSITE NAME: {website_name}
PRODUCT TITLE: {product_data.get('title', 'Unknown')}
PRODUCT URL: {product_data.get('url', '')}

PRICES FOUND: {json.dumps(product_data.get('prices', []))}

DESCRIPTION FROM PAGE:
{product_data.get('description', 'No description found')[:5000]}

SPECIFICATION TABLES:
{json.dumps(product_data.get('tables', []), indent=2)[:5000]}

VARIANTS/OPTIONS FOUND:
{json.dumps(product_data.get('variants', []), indent=2)[:3000]}

BREADCRUMBS: {' > '.join(product_data.get('breadcrumbs', []))}

FULL PAGE TEXT (for additional context):
{product_data.get('full_text', '')[:8000]}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": LISTING_SYSTEM_PROMPT},
            {"role": "user", "content": f"Create a Shopify product listing from this scraped product data:\n\n{context}"}
        ],
        temperature=0.3,
        response_format={"type": "json_object"},
        max_tokens=4000,
    )

    result = json.loads(response.choices[0].message.content)
    return result


def generate_product_image(prompt):
    """Generate a product image using Gemini 2.0 Flash."""
    if not gemini_client:
        init_gemini()

    response = gemini_client.models.generate_content(
        model="gemini-2.0-flash-exp-image-generation",
        contents=prompt,
        config=genai.types.GenerateContentConfig(
            response_modalities=["IMAGE", "TEXT"],
        ),
    )

    # Extract image from response
    for part in response.candidates[0].content.parts:
        if part.inline_data and part.inline_data.mime_type.startswith("image/"):
            return part.inline_data.data
    
    raise Exception("No image generated by Gemini")


def generate_images_for_product(listing_data, log_callback=None):
    """Generate both product images and return as list of image bytes."""
    images = []
    
    if not os.getenv("GEMINI_API_KEY"):
        if log_callback:
            log_callback("⚠️ GEMINI_API_KEY not set — skipping image generation")
        return images
    
    prompt1 = listing_data.get("image_prompt_1", "")
    prompt2 = listing_data.get("image_prompt_2", "")
    
    if prompt1:
        try:
            if log_callback:
                log_callback("🎨 Generating image 1 (primary) with Gemini...")
            img1 = generate_product_image(prompt1)
            images.append({"data": img1, "filename": "product-main.png", "type": "primary"})
            if log_callback:
                log_callback("✅ Image 1 generated")
        except Exception as e:
            if log_callback:
                log_callback(f"❌ Image 1 failed: {e}")
    else:
        if log_callback:
            log_callback("⚠️ No image_prompt_1 in AI response — skipping image 1")
    
    if prompt2:
        try:
            if log_callback:
                log_callback("🎨 Generating image 2 (use-case) with Gemini...")
            img2 = generate_product_image(prompt2)
            images.append({"data": img2, "filename": "product-usecase.png", "type": "use-case"})
            if log_callback:
                log_callback("✅ Image 2 generated")
        except Exception as e:
            if log_callback:
                log_callback(f"❌ Image 2 failed: {e}")
    else:
        if log_callback:
            log_callback("⚠️ No image_prompt_2 in AI response — skipping image 2")
    
    return images
